# Generated by Django 5.2.14 on 2026-05-26 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='file',
            field=models.FileField(upload_to='clues/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'mp3', 'wav', 'm4a'])], verbose_name='첨부파일'),
        ),
    ]
